version: '3.4'

services:
    backend:
        image: backend
        build:
            context: packages/backend
            dockerfile: ./Dockerfile
            target: production
        environment:
            NODE_ENV: production
            PORT: 9999
        stdin_open: true
        tty: true
        expose:
            - 9999
        ports:
            - 9999:9999
            - 9229:9229
        networks:
            - app-network
        command: [ "node", "build/index.js" ]

volumes:
    appdata: null
networks:
    app-network:
        driver: bridge
