version: '3.4'

services:
  backend:
    image: backend
    build:
      context: backend
      dockerfile: ./Dockerfile
      target: base
    environment:
      NODE_ENV: development
      PORT: 9999
    stdin_open: true
    tty: true
    expose:
      - 9999
    volumes:
      - "./backend/src:/home/node/app/src"
    ports:
      - 9999:9999
      - 9229:9229
    networks:
      - app-network
    command: ["yarn", "start"]

volumes:
  appdata:

networks:
  app-network:
    driver: bridge
  
