version: '3.4'

services:
  backend:
    image: backend
    build:
      context: backend
      dockerfile: ./Dockerfile
      target: base
    environment:
      NODE_ENV: development
      PORT: 9999
    depends_on:
      - database
    expose:
      - 9999
    volumes:
      - "./backend/src:/home/node/app/src"
    ports:
      - 9999:9999
      - 9229:9229
    networks:
      - app-network
    command: ["yarn", "start"]
  database:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=app
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - appdata:/data/db
    ports:
      - 27017:27017
    restart: always
    networks:
      - app-network

volumes:
  appdata:

networks:
  app-network:
    driver: bridge
  
