version: '3.4'

services:
  backend:
    image: notekunn/kma-news-backend
    build:
      context: .
      dockerfile: Dockerfile
      target: product
    expose:
      - 8080
    command: yarn backend deploy

  frontend:
    image: notekunn/kma-news-frontend
    build:
      context: .
      dockerfile: Dockerfile
      target: static_product
      args:
        BUILD_CONTEXT: frontend
        API_URL: "https://${BACKEND_HOST}"
        ZALO_APP_ID: "${ZALO_APP_ID}"
        ZALO_CALLBACK_URL: "https://${FRONTEND_HOST}"
    command: [ "nginx", "-g", "daemon off;" ]

  admin:
    image: notekunn/kma-news-admin
    build:
      context: .
      dockerfile: Dockerfile
      target: static_product
      args:
        BUILD_CONTEXT: admin
        API_URL: "https://${BACKEND_HOST}"
    expose:
      - 80
    command: [ "nginx", "-g", "daemon off;" ]
  crawler:
    image: notekunn/kma-news-crawler
    container_name: kma-news-crawler
    build:
      context: .
      dockerfile: Dockerfile
      target: product
      args:
        BUILD_CONTEXT: crawler
    command: yarn crawler deploy
