name: ci

on:
  push:
    branches:
      - 'main'
      - 'hotfix'
  workflow_dispatch:
jobs:
  build-backend:
    name: 'Build backend'
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: notekunn/kma-news-backend:latest
          target: product
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GH_TOKEN }}
          build-args: |
            BUILD_CONTEXT=backend
  build-frontend:
    name: 'Build frontend'
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: notekunn/kma-news-frontend:latest
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GH_TOKEN }}
          target: static_product
          build-args: |
            BUILD_CONTEXT=frontend
            API_URL=https://${{secrets.BACKEND_HOST}}
            ZALO_APP_ID=${{secrets.ZALO_APP_ID}}
            ZALO_CALLBACK_URL=https://${{secrets.FRONTEND_HOST}}
  build-admin:
    name: 'Build admin'
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: notekunn/kma-news-admin:latest
          target: static_product
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GH_TOKEN }}
          build-args: |
            BUILD_CONTEXT=admin
            API_URL=https://${{secrets.BACKEND_HOST}}
  build-crawler:
    name: 'Build crawler'
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: notekunn/kma-news-crawler:latest
          target: product
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GH_TOKEN }}
          build-args: |
            BUILD_CONTEXT=crawler
  deploy:
    needs: [build-backend, build-frontend, build-admin, build-crawler]
    name: Auto deploy to vps
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/kma-news
            git pull
            git reset --hard origin/main 
            docker-compose -f docker-compose.prod.yml down
            docker-compose -f docker-compose.prod.yml pull            
            docker-compose -f docker-compose.prod.yml up -d
